### ISSUE TITLE
archive this repository?

### ISSUE THREAD

**Issue by tfoote** [ros2/depthimage_to_laserscan#10]
Since #9 it's been pushed back to upstream. I updated the description but it would probably make sense to archive this project.

**Comment by clalancette** [comment]
I'm currently waiting to get permission bits to the upstream repository.  Once I have that, I'll do a release of the upstream sources into crystal.  With that done, I'll make a last commit to this repository with a README describing the situation, then archive the whole thing.

**Comment by clalancette** [comment]
All right, I've made the release from the new repository, so closing this and archiving.
